name: 💰 Reward Task
description: Task issue with Reward
title: '[Reward] '
labels:
    - reward
body:
    - type: markdown
      attributes:
          value: This form is created from https://github.com/idea2app/GitHub-reward

    - type: textarea
      id: description
      attributes:
          label: Task description
      validations:
          required: true

    - type: input
      id: source
      attributes:
          label: Task source
          description: URL from an External System
          placeholder: https://example.com/task/123

    - type: input
      id: reward
      attributes:
          label: Reward
          description: Please enter the reward details (e.g. 500 CNY, 50 USD, Exclusive Badge, Custom Gift)
          placeholder: 500 CNY / Official Badge
      validations:
          required: true

    - type: input
      id: payer
      attributes:
          label: Reward payer
          description: GitHub username of the payer (optional, defaults to issue creator)
      validations:
          required: false
